name: build fonts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build MGCB
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install MGCB
      run: dotnet tool install --global dotnet-mgcb --version 3.8.0.1641

    - name: Cache multiple paths
      continue-on-error: true
      uses: actions/cache@v2
      with:
        path: ./obj
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Build MGCB
      continue-on-error: true
      run: mgcb ./font.mgcb

    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: artifacts
        path: ./Artifacts